# Training description


# Gerenal options
log_file: logs/training_resnet_0.log
seed: 1988
deterministic: false
epochs: 64
lr: 0.001
patience: 100

multi_gpu: false
num_cpu: 5

mixed_precision: true
clipping: false

# Optimizer and scheduler options
optimizer: 
    type: adam
    options: 

scheduler:
    type: CyclicLR
    options: 


# Evaluation options
compute_test_eer: true
log_interval: 461
validation_frequency: 1

# Save options
tmp_model_name: models/tmp_model_2s_cuda_0_.pt
best_model_name: models/best_model_2s_cuda_0_.pt
checkpoint_frequency: 10
